import assert from 'node:assert/strict';

export async function checkNotificationRecipientPicker({ page, context, token, go, visible, shot }) {
  const lookups = [];
  let fail = false, releaseSlow;
  const slow = new Promise(resolve => { releaseSlow = resolve; });
  const handler = async route => {
    const request = route.request(), query = request.postDataJSON();
    assert.equal(request.headers().authorization, `Bearer ${token}`);
    assert.equal(query.take, 10, 'The client never downloads the whole user directory');
    lookups.push(query);
    if (fail) return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Search unavailable' }) });
    if (query.filter === 'slow') await slow;
    const matches = query.filter === 'none' ? [] : query.filter === 'ava' ? [{ id: 90001, name: 'Ava', surname: 'Nkosi', email: 'ava@example.invalid', isActive: true }]
      : query.filter === 'slow' ? [{ id: 90002, name: 'Stale', email: 'stale@example.invalid' }]
      : Array.from({ length: 10 }, (_, index) => ({ id: query.skip + index + 1, name: 'Member', surname: String(query.skip + index + 1), email: `member${query.skip + index + 1}@example.invalid`, isActive: true }));
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ items: matches, totalCount: query.filter ? matches.length : 12500 }) }).catch(() => {});
  };
  await context.route('**/api/idp/qa/admin/users/list', handler);
  const settle = () => page.waitForTimeout(350); // Past the debounce window; proves that no background request started.
  try {
    await go('/app-notifications');
    await page.getByRole('button', { name: 'Create notification', exact: true }).click();
    const composer = page.getByRole('dialog', { name: 'Create notification', exact: true });
    const search = composer.getByRole('combobox', { name: 'Search app users', exact: true });
    await visible(search); await settle();
    assert.equal(lookups.length, 0, 'Opening the composer does not query users');
    assert.equal(await search.getAttribute('aria-expanded'), 'false');
    assert.equal(await composer.getByRole('listbox').count(), 0);
    const styleY = (await composer.getByLabel('Alert style', { exact: true }).boundingBox()).y;
    await search.focus();
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select member1@example.invalid', exact: true }));
    assert.deepEqual(lookups.at(-1), { filter: '', skip: 0, take: 10 });
    assert.equal(await composer.getByRole('listbox').getByRole('option').count(), 10);
    assert.ok(Math.abs((await composer.getByLabel('Alert style', { exact: true }).boundingBox()).y - styleY) < 2, 'Dropdown does not push form fields down');
    await shot('notification-user-dropdown');
    await composer.getByRole('button', { name: 'More users', exact: true }).click();
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select member11@example.invalid', exact: true }));
    assert.equal(lookups.at(-1).skip, 10);
    await composer.getByRole('button', { name: 'Previous users', exact: true }).click();
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select member1@example.invalid', exact: true }));
    const beforeTyping = lookups.length;
    await search.fill('a'); await search.fill('av'); await search.fill('ava');
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select ava@example.invalid', exact: true }));
    assert.equal(lookups.length, beforeTyping + 1, 'Typing is debounced into one lookup');
    assert.deepEqual(lookups.at(-1), { filter: 'ava', skip: 0, take: 10 });
    await search.press('Escape');
    assert.equal(await search.getAttribute('aria-expanded'), 'false');
    assert.equal(await composer.isVisible(), true, 'Escape dismisses the dropdown first');
    await search.click();
    await search.fill('blurred');
    await composer.getByLabel('Title', { exact: true }).focus(); await settle();
    assert.equal(lookups.some(query => query.filter === 'blurred'), false, 'Blur cancels the queued lookup');
    assert.equal(await composer.getByRole('listbox').count(), 0);
    const slowStarted = page.waitForRequest(request => request.url().endsWith('/admin/users/list') && request.postDataJSON().filter === 'slow');
    await search.fill('slow'); await slowStarted;
    await search.fill('ava');
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select ava@example.invalid', exact: true }));
    releaseSlow(); await settle();
    assert.equal(await composer.getByRole('listbox').getByRole('option').count(), 1);
    assert.equal(await composer.getByRole('listbox').getByRole('option', { name: 'Select stale@example.invalid', exact: true }).count(), 0, 'A late response cannot replace the current search');
    fail = true; await search.fill('failure');
    await visible(composer.getByRole('button', { name: 'Retry search', exact: true }));
    fail = false; await composer.getByRole('button', { name: 'Retry search', exact: true }).click();
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select member1@example.invalid', exact: true }));
    await search.fill('none');
    await visible(composer.getByText('No matching app users.', { exact: true }));
    assert.equal(await composer.getByRole('listbox').getByRole('option').count(), 0);
    await search.fill('ava');
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select ava@example.invalid', exact: true }));
    await search.press('ArrowDown');
    const active = await search.getAttribute('aria-activedescendant');
    assert.equal(active, await composer.getByRole('listbox').getByRole('option').getAttribute('id'));
    await search.press('Enter');
    const change = composer.getByRole('button', { name: 'Change user', exact: true });
    await visible(change);
    assert.equal(await change.evaluate(el => el === document.activeElement), true);
    assert.equal(await composer.getByRole('listbox').count(), 0);
    const selectedCount = lookups.length;
    await composer.getByLabel('Title', { exact: true }).fill('Recipient test');
    await composer.getByLabel('Message', { exact: true }).fill('Test message');
    await composer.getByRole('button', { name: 'Review notification', exact: true }).click();
    const review = page.getByRole('dialog', { name: 'Review notification', exact: true });
    await visible(review.getByText('Recipient: ava@example.invalid · Sandbox', { exact: true }));
    await review.getByRole('button', { name: 'Back to edit', exact: true }).click();
    await composer.getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByRole('button', { name: 'Create notification', exact: true }).click();
    await visible(change); await settle();
    assert.equal(lookups.length, selectedCount, 'Selection, review and reopening do not start another lookup');
    await change.click();
    assert.equal(await search.evaluate(el => el === document.activeElement), true);
    await search.fill('broadcast-cancelled');
    await composer.getByLabel('Recipients', { exact: true }).selectOption('all'); await settle();
    assert.equal(lookups.some(query => query.filter === 'broadcast-cancelled'), false);
    const broadcastCount = lookups.length;
    await composer.getByLabel('Recipients', { exact: true }).selectOption('user'); await settle();
    assert.equal(lookups.length, broadcastCount, 'Changing audience does not open the lookup');
    await search.fill('');
    await visible(composer.getByRole('listbox').getByRole('option', { name: 'Select member1@example.invalid', exact: true }));
    const theme = await page.evaluate(() => document.documentElement.dataset.theme);
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
    await shot('notification-user-dropdown-dark');
    await page.evaluate(theme => { document.documentElement.dataset.theme = theme; }, theme);
    await page.setViewportSize({ width: 360, height: 720 });
    await shot('notification-user-dropdown-mobile');
    const menuBounds = await composer.locator('.recipient-dropdown').boundingBox(), dialogBounds = await composer.boundingBox();
    assert.ok(menuBounds.x >= dialogBounds.x && menuBounds.x + menuBounds.width <= dialogBounds.x + dialogBounds.width);
    assert.ok(menuBounds.y >= dialogBounds.y && menuBounds.y + menuBounds.height <= dialogBounds.y + dialogBounds.height, 'Dropdown is not clipped by the modal');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await search.press('Escape');
    const closingCount = lookups.length;
    await search.click(); await search.fill('closing-cancelled');
    await composer.getByRole('button', { name: 'Close', exact: true }).click(); await settle();
    assert.equal(lookups.length, closingCount, 'Closing the dialog cancels pending search');
    await page.setViewportSize({ width: 1440, height: 1000 });
    console.log('PASS lazy recipient lookup, 12,500-user pagination, debounce/cancellation, stale responses, retry, keyboard selection, retained recipient and mobile/dark dropdown');
  } finally {
    releaseSlow();
    await context.unroute('**/api/idp/qa/admin/users/list', handler);
  }
}
