import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

export async function checkAccountSecurity({ page, context, token, go, visible, shot }) {
  let status = { email: 'admin@example.invalid', isEmailConfirmed: false, twoFactorEnabled: false, recoveryCodesRemaining: 0 };
  let unavailable = false;
  const calls = [];
  const codes = Array.from({ length: 10 }, (_, i) => `ABCDE-12345-ABCDE-${String(i).padStart(5, '0')}`);
  const png = await fs.readFile(new URL('./fixtures/authenticator-setup.png', import.meta.url));
  const handler = async route => {
    const request = route.request(), action = new URL(request.url()).pathname.split('/').pop();
    assert.equal(request.headers().authorization, `Bearer ${token}`);
    let body; try { body = request.postDataJSON(); } catch { /* GET */ }
    calls.push({ action, body });
    const reply = (value, code = 200) => route.fulfill({ status: code, json: value });
    if (unavailable) return reply({ message: 'Account security is unavailable on this server.' }, 404);
    if (action === 'security') return reply(status);
    if (action === 'setup') return reply({ manualEntryKey: 'JBSWY3DPEHPK3PXP', authenticatorUri: 'otpauth://totp/Cloudgate:admin@example.invalid?secret=JBSWY3DPEHPK3PXP', expiresAtUtc: new Date(Date.now()+600000).toISOString(), qrCodeDataUrl: `data:image/png;base64,${png.toString('base64')}` });
    if (body?.code !== '123456') return reply({ message: 'Invalid or already used code.' }, 400);
    if (action === 'enable') status = { ...status, twoFactorEnabled: true, recoveryCodesRemaining: 10 };
    if (action === 'disable') status = { ...status, twoFactorEnabled: false, recoveryCodesRemaining: 0 };
    return reply({ security: status, recoveryCodes: action === 'disable' ? null : codes, tokens: action === 'recovery-codes' ? null : { accessToken: token, refreshToken: 'qa-refresh', expiresIn: 3600 } });
  };
  await context.route('https://api.example.invalid/api/idp/qa/account/security**', handler);
  await go('/');
  assert.equal(await page.locator('.app-sidebar .user-card').count(), 0);
  const trigger = page.locator('.workspace-bar .account-trigger');
  assert.match(await trigger.getAttribute('aria-label'), /Alex Admin, Admin/);
  await trigger.focus(); await page.keyboard.press('ArrowDown');
  const menu = page.getByRole('menu', { name: 'My account' }); await visible(menu);
  assert.equal(await menu.evaluate(el => getComputedStyle(el).position), 'absolute');
  assert.ok((await page.locator('.workspace-bar').boundingBox()).height <= 50, 'Opening the account dropdown must not enlarge the header');
  assert.deepEqual(await menu.getByRole('menuitem').allTextContents(), ['Profile', 'Change profile picture', 'Settings', 'About', 'Log out']);
  assert.equal(await menu.getByRole('menuitem', { name: 'Profile', exact: true }).evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('End'); assert.equal(await menu.getByRole('menuitem', { name: 'Log out' }).evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Home'); await page.keyboard.press('ArrowDown'); await page.keyboard.press('ArrowDown');
  assert.equal(await menu.getByRole('menuitem', { name: 'Settings', exact: true }).evaluate(el => el === document.activeElement), true);
  await shot('account-menu-desktop');
  await page.keyboard.press('Escape'); assert.equal(await menu.count(), 0); assert.equal(await trigger.evaluate(el => el === document.activeElement), true);
  await trigger.click(); await page.locator('.workspace-breadcrumb').click(); assert.equal(await menu.count(), 0);
  await trigger.click(); await menu.getByRole('menuitem', { name: 'Profile', exact: true }).click(); await visible(page.getByLabel('First name'));
  await trigger.click(); await menu.getByRole('menuitem', { name: 'Settings', exact: true }).click();
  await visible(page.getByText('Not confirmed', { exact: true })); await visible(page.getByText('Off', { exact: true }));
  assert.equal(await page.locator('.account-security-section').first().evaluate(el => getComputedStyle(el).padding), '20px');
  await shot('account-settings-desktop');
  status.isEmailConfirmed = true; await page.getByRole('button', { name: 'Refresh security status' }).click(); await visible(page.getByText('Confirmed', { exact: true }));
  await page.getByRole('button', { name: 'Set up 2FA' }).click(); await visible(page.getByText('JBSWY3DPEHPK3PXP', { exact: true }));
  assert.equal(await page.getByRole('img', { name: 'Scan with your authenticator app to add this account' }).evaluate(el => el.complete && el.naturalWidth > 0), true);
  await shot('authenticator-setup-desktop');
  await page.getByLabel('Authenticator code', { exact: true }).fill('000000'); await page.getByRole('button', { name: 'Enable 2FA', exact: true }).click();
  await visible(page.getByRole('alert')); assert.match(await page.getByRole('alert').textContent(), /Invalid/);
  await page.getByLabel('Authenticator code', { exact: true }).fill('123456'); await page.getByRole('button', { name: 'Enable 2FA', exact: true }).click();
  await visible(page.getByRole('heading', { name: 'Save your recovery codes' })); assert.equal(await page.locator('.account-recovery-codes code').count(), 10);
  assert.equal(await page.evaluate(() => Object.values(localStorage).join(' ').includes('ABCDE-12345')), false);
  await shot('authenticator-recovery-codes');
  await page.getByRole('button', { name: 'I saved my codes' }).click();
  await page.getByRole('button', { name: 'Replace recovery codes' }).click(); await page.getByLabel('Authenticator or recovery code', { exact: true }).fill('123456');
  await page.getByRole('button', { name: 'Replace codes', exact: true }).click(); await visible(page.getByRole('heading', { name: 'Save your recovery codes' }));
  await page.getByRole('button', { name: 'I saved my codes' }).click();
  await page.getByRole('button', { name: 'Turn off 2FA' }).click(); await page.getByLabel('Authenticator or recovery code', { exact: true }).fill('123456');
  await page.getByRole('button', { name: 'Confirm turn off', exact: true }).click(); await visible(page.getByText('Off', { exact: true }));
  await page.evaluate(() => document.documentElement.classList.add('dark')); await trigger.click(); await shot('account-menu-dark'); await page.keyboard.press('Escape'); await shot('account-settings-dark');
  await page.evaluate(() => document.documentElement.classList.remove('dark'));
  await page.setViewportSize({ width: 390, height: 844 }); await page.locator('.app-bar .account-trigger').click(); await shot('account-menu-mobile');
  await menu.getByRole('menuitem', { name: 'Settings', exact: true }).click(); await page.getByRole('button', { name: 'Set up 2FA' }).click();
  await visible(page.getByLabel('Authenticator code', { exact: true })); await shot('account-settings-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await page.setViewportSize({ width: 1440, height: 1000 });
  unavailable = true; await go('/account/settings'); await visible(page.getByRole('alert')); assert.equal(await page.getByText('Off', { exact: true }).count(), 0);
  unavailable = false; await page.getByRole('button', { name: 'Try again' }).click(); await visible(page.getByText('Off', { exact: true }));
  await trigger.click(); await menu.getByRole('menuitem', { name: 'About', exact: true }).click(); assert.equal(new URL(page.url()).pathname, '/about');
  await context.route('https://hub.example.invalid/idp/qa/login**', route => route.fulfill({ contentType: 'text/html', body: '<h1>Hosted sign in</h1>' }));
  await trigger.click(); await menu.getByRole('menuitem', { name: 'Log out', exact: true }).click();
  await page.waitForURL('https://hub.example.invalid/idp/qa/login**');
  const appStorage = (await context.storageState()).origins.find(value => value.origin === 'http://127.0.0.1:3199');
  assert.equal(appStorage?.localStorage.some(item => item.name === 'idp_access_token' || item.name === 'idp_refresh_token') || false, false);
  assert.equal(calls.filter(call => call.action === 'enable').length, 2);
  await context.unroute('https://api.example.invalid/api/idp/qa/account/security**', handler);
  await go('/');
  console.log('PASS account menu keyboard/outside-click navigation and logout; email status; 2FA setup, errors, recovery and disable; unavailable API; mobile and dark layouts');
}
